# Generated by Django 5.1.1 on 2024-09-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_inmuebles_m2_terreno_inmuebles_numero_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
