# Generated by Django 5.1.1 on 2024-09-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_inmuebles_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebles',
            name='imagen',
        ),
    ]
